#!/usr/bin/env python3


from core.radioLink import radioLink


radioLnk: radioLink = radioLink()
radioLnk.init()


def init_lora():
   pass


def main():
   # radioLink.setPins(reset=RST_PIN)
   pass


# -- -- -- entry point -- -- --
if __name__ == "__main__":
   main()
