#!/usr/bin/env python3


from radio.sx127x import sx127x


def init_lora():
   pass


def main():
   # radioLink.setPins(reset=RST_PIN)
   pass


# -- -- -- entry point -- -- --
if __name__ == "__main__":
   main()
