#!/usr/bin/env python3

# import LoRaRF as lora
from LoRaRF import SX127x


RST_PIN: int = 22

radioLink: SX127x = SX127x()
radioLink.setPins(reset=RST_PIN)
radioLink.begin()


def init_lora():
   pass


def main():
   # radioLink.setPins(reset=RST_PIN)
   pass


# -- -- -- entry point -- -- --
if __name__ == "__main__":
   main()
