#!/usr/bin/env python3

import os, sys, spidev
from radio.sx127x.loraSPI import loraSPI


thispy, _bid, _bdev, _hz = sys.argv
print(f"\n[{thispy}]\n")

b_id: int = int(_bid)
b_dev: int = int(_bdev)
b_hz: int = int(_hz)


loraspi: loraSPI = loraSPI(pin_rst=22, pin_cs=8, bus=b_id, bus_dev=b_dev, speed=b_hz)
print(dir(loraspi))
loraspi.rst()
