#!/usr/bin/env python3
import time

from loraSPI import loraSPI
from sx127x import sx127x

bus: int = 0
dev: int = 0
# spi_hz: int = 3900000
# spi_hz: int = 7800000
# spi_hz: int = 488000
spi_hz: int = 8000000


spi: loraSPI = loraSPI(bus=bus, bus_dev=dev, speed=spi_hz)
print(spi.dump())
time.sleep(4.0)
spi.init()

dev: sx127x = sx127x(spi=spi, rst_pin=22, cs_pin=8)
dev.init()
dev.reset()
